version: "3"
services:
  content:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/myapp
      - /myapp/node_modules
    environment:
      - PORT=3000
    depends_on:
      - mongocontent
  mongocontent:
    image: mongo
    volumes:
      - mongo-db-content:/data/db
volumes:
  mongo-db-content:

networks:
  default:
    external:
      name: bridge-network