version: "3"
services:
  content-service-cont:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/myapp
      - /myapp/node_modules
    environment:
      - PORT=3000
    depends_on:
      - mongo
  mongo:
    image: mongo
    # environment:
    #   - MONGO_INIT_ROOT_USERNAME=yash
    #   - MONGO_INIT_ROOT_USERNAME=mypassword  
    volumes:
      - mongo-db:/data/db
volumes:
  mongo-db: